computer/urls.py
from django.urls import path
from . import views

app_name="chub"

urlpatterns = [
    # path('',views.IndexView.as_view(), name='index'),

    # path('brand_create-form/', views.CompBrandCreateView.as_view(), name= 'brand-create-form'),
    path('brand_create-form/', views.ComputerBrandView.as_view(), name= 'brand-create-form'),       #using only View class

    # path('generation_create-form/', views.CompGenerationCreateView.as_view(), name= 'gen-create-form'),
    path('generation_create-form/', views.ComputerGenerationView.as_view(), name= 'gen-create-form'),   #using only View class

    path('create-form/', views.ComputerCreateView.as_view(), name= 'create-form'),

    # path('brand-list',views.CompBrandListView.as_view(), name='brand-list'),
    path('brand-list',views.ComputerBrandPageView.as_view(), name='brand-list'),        #using only View class

    # path('gen-list/', views.CompGenListView.as_view(), name= 'genlist'),
    path('gen-list/', views.ComputerGenerationPageView.as_view(), name= 'genlist'),     #using only View class

    path('', views.ComputerListView.as_view(), name= 'index'),

    # path('brand-update/<int:pk>',views.CompBrandUpdateView.as_view(), name='brand-update'),
    path('brand-update/<int:pk>',views.ComputerBrandUpdateView.as_view(), name='brand-update'),     #using only View class

    # path('gen-update/<int:pk>',views.CompGenUpdateView.as_view(), name='gen-update'),
    path('gen-update/<int:pk>',views.ComputerGenerationUpdateView.as_view(), name='gen-update'),    #using only View class

    path('update/<int:pk>', views.ComputerUpdateView.as_view(), name= 'update'),

    # path('brand-delete/<int:pk>', views.CompBrandDeleteView.as_view(), name='brand-delete'),
    path('delete/<int:pk>', views.ComputerBrandDeleteView.as_view(), name= 'brand-delete'),     #using only View class

    # path('gen-delete/<int:pk>', views.CompGenDeleteView.as_view(), name='gen-delete'),
    path('gen-delete/<int:pk>', views.ComputerGenerationDeleteView.as_view(), name='gen-delete'),   #using only View class


    path('delete/<int:pk>', views.ComputerDeleteView.as_view(), name= 'delete'),

]

computerhub/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
#  above import of modules:- /settings and static/ - for image file to work


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('computer.urls',namespace='chub')),

]

if settings.DEBUG:
    urlpatterns+= static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

computer/models.py
from django.db import models
from django.urls import reverse

class ComputerBrand (models.Model):
    brand_name= models.CharField(max_length=30)
    logo= models.ImageField(null=True, upload_to="uploadimages/")

    def __str__(self):
        return self.brand_name
        # to check self --> id
        # return f'ID:{self.id}, {self.brand_name}'
    
    # You can use this get_absolute_url(self) function, instead of using success_url in CreateView and UpdateView IN views.py
    
    # def get_absolute_url(self):
    #     return reverse("chub:brand-list", kwargs={"pk": self.pk})
    

class ComputerGeneration (models.Model):
    generation= models.CharField(max_length=20, unique=True)
    price_min= models.IntegerField()
    price_max= models.IntegerField()
    RAM= models.IntegerField()
    brands= models.ForeignKey(ComputerBrand,on_delete=models.CASCADE)

    def __str__(self):
        return self.generation
        # to check self--> id
        # return f'ID:{self.id}, {self.generation}'


class Computer (models.Model):
    computer_code=models.CharField(max_length=30, unique=True)
    computer= models.ForeignKey(ComputerGeneration, on_delete=models.CASCADE)
    quantity= models.IntegerField()
    unit_rate= models.IntegerField()
    total_price= models.FloatField()

    def __str__(self):
        return f'selfID:{self.id}--> computer code:{self.computer_code}'

computer/forms.py
from django import forms
from .models import Computer,ComputerBrand, ComputerGeneration


class ComputerBrandForm(forms.ModelForm):
    class Meta:
        model= ComputerBrand
        fields="__all__"
        

class ComputerGenerationForm(forms.ModelForm):
    class Meta:
        model= ComputerGeneration
        fields= "__all__"

computer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View,CreateView, ListView, UpdateView, TemplateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Computer, ComputerGeneration, ComputerBrand
from .forms import ComputerBrandForm, ComputerGenerationForm
# from django.contrib.auth.mixins import LoginRequiredMixin


# class IndexView(TemplateView):
#     template_name= "computer/index.html"


#USING VIEW CLASS ONLY.
class ComputerBrandView(View):
    def get(self,request):
        form= ComputerBrandForm()
    
        return render(request,'computer/computerbrand_form.html',{
            'form':form,
        })
    
    def post(self,request):
        form= ComputerBrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            
        return redirect('chub:brand-list')
    
        # return render(request,'computer/computerbrand_list.html', {
        #     'form': form,
        # })
    

class ComputerBrandUpdateView(View):
    def get(self, request, pk):
        item= get_object_or_404(ComputerBrand, pk=pk)
        form= ComputerBrandForm(instance=item)

        return render (request, 'computer/computerbrand_form.html', {
            'form':form,
        })

    def post(self, request, pk):
        item = get_object_or_404(ComputerBrand, pk= pk)

        form= ComputerBrandForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('chub:brand-list')
        
        # return render(request,'computer/computerbrand_form.html', {
        #     'form': form,
        # })
    

class ComputerBrandDeleteView(View):
    def get(self,request, pk):
        form= get_object_or_404(ComputerBrand, pk=pk)

        return render(request, 'computer/computerbrand_confirm_delete.html',{
            'form':form,
        })

    def post(self,request, pk):
        form=get_object_or_404(ComputerBrand, pk=pk)
        form.delete()

        return redirect('chub:brand-list')
        

# to show list of computer brand
class ComputerBrandPageView(View):
    def get(self, request):
        form = ComputerBrand.objects.all()

        return render(request, 'computer/computerbrand_list.html', {
            'brand_list':form,
        })


class ComputerGenerationView(View):
    def get(self, request):
        form= ComputerGenerationForm()

        return render(request,'computer/computergeneration_form.html',{
            'form':form,
        })

    def post(self, request):
        form=ComputerGenerationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chub:genlist')
        
        # return render(request, 'computer/computergeneration_form.html', {
        #     'form': form,
        # })


class ComputerGenerationUpdateView(View):
    def get(self,request,pk):
        item= get_object_or_404(ComputerGeneration, pk=pk)
        form= ComputerGenerationForm(instance=item)

        return render(request, 'computer/computergeneration_form.html', {
            'form':form
        })
        
    def post(self, request, pk):
        item= get_object_or_404(ComputerGeneration,pk=pk)
        form= ComputerGenerationForm(request.POST, instance=item)

        if form.is_valid():
            form.save()
            return redirect('chub:genlist')
        
        # return render (request,'computer/computergeneration_form.html', {
        #     'form': form,
        # })
    

class ComputerGenerationDeleteView(View):
    def get(self, request, pk):
        item= get_object_or_404(ComputerGeneration,pk=pk)
        
        return render (request, 'computer/computergeneration_confirm_delete.html', {
            'form':item
        })
    
    def post(self, request, pk):
        item= get_object_or_404(ComputerGeneration, pk=pk)
        item.delete()

        return redirect('chub:genlist')


class ComputerGenerationPageView(View):
    def get(self, request):
        form= ComputerGeneration.objects.all()

        return render(request,'computer/computergeneration_list.html', {
            'gen_list':form,
        })
    


# USING CREATEVIEW 

# class CompBrandCreateView(CreateView):
#     model=ComputerBrand
#     fields="__all__"
#     success_url= reverse_lazy("chub:brand-list")

class CompGenerationCreateView(CreateView):
    model=ComputerGeneration
    fields= "__all__"
    success_url= reverse_lazy('chub:genlist')

class ComputerCreateView(CreateView):
    model= Computer
    fields= "__all__"
    success_url= reverse_lazy('chub:index')   
    

#using ListView

# class CompBrandListView(ListView):
#     model= ComputerBrand
#     context_object_name= "brand_list"

class CompGenListView(ListView):
    model= ComputerGeneration
    context_object_name= 'gen_list'

class ComputerListView(ListView):
    model= Computer
    context_object_name= 'comp_list'


# using UpdateView

# class CompBrandUpdateView(UpdateView):
#     model= ComputerBrand
#     fields= "__all__"
#     success_url= reverse_lazy('chub:brand-list')

class CompGenUpdateView(UpdateView):
    model=ComputerGeneration
    fields="__all__"
    success_url= reverse_lazy('chub:genlist')

class ComputerUpdateView(UpdateView):
    model= Computer
    fields= "__all__"
    success_url= reverse_lazy('chub:index')


# using DeleteView

# class CompBrandDeleteView(DeleteView):
#     model= ComputerBrand
#     success_url= reverse_lazy('chub:brand-list')

class ComputerDeleteView(DeleteView):
    model= Computer
    success_url= reverse_lazy('chub:index')

class CompGenDeleteView(DeleteView):
    model= ComputerGeneration
    success_url= reverse_lazy('chub:genlist')

computer/templates/computer/computer_confirm_delete.html
{%extends "computer/index.html"%}
{%block title%} Deleting Computer {% endblock%}

{% block content %}
</h3>Are you sure about deleting the data?</h3>
<p>Computer code: {{computer}}</p>

<form method="POST">
    {% csrf_token %}
    <input type= "submit" value= "Confirm Delete">
</form>
{% endblock %}

computer/templates/computer/computer_form.html
{% extends "computer/index.html" %}

{% block title %}
    Add Computer Form
{% endblock %}

{% comment %} {% block content %}
    <div class="d-flex flex-column">
        <div class="mb-3">
            <h4>Fill the form to add/update</h4>
        </div>
        <div>
            
                <form method='POST'>
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type= 'submit' value= 'Submit'>
            
        </div>
    </div>
{% endblock content %} {% endcomment %}



{% block content %}
    <div class = "row justify-content-center ">
        <div class="col-lg-4">
            <form method= "POST" enctype= "multipart/form-data" >
                {% csrf_token %}

                <div class="mb-3">
                    <label for="{{ form.computer_code.id_for_label }}" class="form-label">Computer Code:</label>
                    <input type="text" class="form-control" name="{{ form.computer_code.name }}" id="{{ form.computer_code.id_for_label }}" value="{% if form.computer_code.value %} {{ form.computer_code.value}} {% else %} {% endif %}">

                </div>

                <div class=" mb-3">
                    <label for="{{ form.quantity.id_for_label }}" class="form-label">Quantity: </label>
                    <input type= "number" class= "form-control" name= "{{ form.quantity.name }}" id= "{{form.quantity.id_for_label}}" value= "{{form.quantity.value}}">
                </div>

                <div class=" mb-3">
                    <label for="{{ form.unit_rate.id_for_label }}" class="form-label">Rate: </label>
                    <input type="number" class="form-control" name="{{ form.unit_rate.name }}" id="{{ form.unit_rate.id_for_label }}" value="{{ form.unit_rate.value }}">
                </div>

                <div class=" mb-3">
                    <label for="{{ form.total_price.id_for_label }}" class="form-label">Total Price: </label>
                    <input class="form-control" name="{{ form.total_price.name }}" type="number" id="{{ form.total_price.id_for_label }}" value= "{{ form.total_price.value }}">
                </div>
                
                <div>{{form.initial}}</div>

                <div class="input-group mb-3">
                    <label class="input-group" for="{{ form.computer.id_for_label }}">Computer Generation:</label>
                    <select class="form-select" id="{{ form.computer.id_for_label }}" name="{{ form.computer.name }}" value= "{{ form.computer.value }}">
                        <option value="" disabled selected >Select a Generation </option>
                        {% for gen in form.computer.field.queryset %}
                            <option value= "{{ gen.pk}}">{{gen.generation}}</option>
                        {% endfor %}
                    </select>
                </div>
                  
                <div>
                    <button class= "btn btn-secondary" type="submit">Submit</button>   
                </div>

            </form>
        </div>
    </div>
{% endblock%} 

computer/templates/computer/computer_list.html
{% extends "computer/index.html" %}
 
{% block title %} Computer Hub {% endblock %}

{% block content %}
<div class="d-flex flex-column">
    <div>
        <a class="btn btn-primary float-end m-3" href='{% url "chub:create-form" %}' role="button">Add Computer</a>
    </div>
    <div class="table-responsive-sm ">
        <table class="table table-striped table-group-divider">
            <thead>
                <tr class='table table-info'>
                    <th scope="col">S.N.</th>
                    <th scope="col">Logo</th>
                    <th scope="col">Brandname</th>
                    <th scope="col">Generation</th>
                    <th scope="col">RAM</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Rate</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>

        {% for comp in comp_list %}
            
            <tbody>
                <tr >
                    <td scope="row">{{forloop.counter}}</td>
                    <td><img src= "{{comp.computer.brands.logo.url}}" class= "img-fluid" alt="..." width="35"></td>
                    <td>{{comp.computer.brands.brand_name}}</td>
                    <td>{{comp.computer.generation}}</td>
                    <td>{{comp.computer.RAM}}</td>
                    <td>{{comp.quantity}}</td>
                    <td>{{comp.unit_rate}}</td>
                    <td><a class="btn btn-secondary btn-sm" href='{% url "chub:update" comp.id %}' role="button">UPDATE</a>
                        <a class = "btn btn-danger btn-sm" href= '{% url "chub:delete" comp.id %}' role= "button">DEL</a> 
                    </td>

                </tr>
                
            </tbody>
        {% endfor %}

        </table>
    </div>

{% endblock %}

computer/templates/computer/computerbrand_confirm_delete.html
{%extends "computer/index.html"%}
{%block title%} Deleting Computer Brand{% endblock%}

{% block content %}
</h3>Are you sure about deleting the computer brand data?</h3>
<p id ="confirm_delete">Computer Brand: {{form}}</p>

<form method="POST">
    {% csrf_token %}
    <input type= "submit" value= "Confirm Delete">
</form>
{% endblock %}

computer/templates/computer/computerbrand_form.html
{% extends "computer/index.html" %}
{% block title %}
Add Computer Brand Form
{% endblock %}


{% comment %} {% block content %}
    <form method='POST' enctype= 'multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
        <input type= 'submit' value= 'Submit'>
    </form>
{% endblock %}  {% endcomment %}


{% block content %}
    <div class = "row justify-content-center ">
        <div class="col-lg-auto">
            <form method="POST" enctype = "multipart/form-data">
                {% csrf_token %}


                <div class="mb-3">
                    <label for="{{form.brand_name.id_for_label}}" class="form-label">Brand Name:</label>
                    <input type="text" class="form-control-auto" name="{{form.brand_name.name}}" id="{{form.brand_name.id_for_label}}" placeholder="Eg: Dell" value= "{% if form.brand_name.value %} {{form.brand_name.value}} {% else %} {% endif %} ">
                </div>
                <div class=" mb-3">
                    <label for="{{form.logo.id_for_label}}" class="form-label">Upload Logo: </label>
                    <input class="form-control-auto" name="{{form.logo.name}}" type="file" id="{{form.logo.id_for_label}}" value="{{form.logo.value}}">
                </div>
                <p>{{form.initial}}</p>

                <div>
                    <button class= "btn btn-secondary" type= "submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock%}

computer/templates/computer/computerbrand_list.html
{% extends "computer/index.html" %}
 
{% block title %} Computer Brand List {% endblock %}

{% block content %}
    <div class= "d-flex flex-column">
        <div>
            <a class="btn btn-primary float-end m-3" href='{% url "chub:brand-create-form" %}' role="button">Add Brand</a>
        </div>
        <div class="table-responsive-sm px-1">
            <table class="table table-striped table-sm" >
                <thead>
                    <tr class="table table-light ">
                        <th scope="col">S.N.</th>
                        <th scope="col">Computer Brand</th>
                        <th scope="col">Logo</th>
                        <th scope="col">Action</th>
                        
                    </tr>
                </thead>

                {% for brand in brand_list %}
                <tbody >
                    <tr >
                        <td scope="row">{{forloop.counter}}</td>
                        <td>{{brand.brand_name}}</td>
                        <td><img src="{{brand.logo.url}}" class= img-fluid width= "120" ></td>
                        <td><a class="btn btn-secondary btn-sm" href='{% url "chub:brand-update" brand.id %}' role="button">UPDATE</a>
                            <a class="btn btn-danger btn-sm" href='{% url "chub:brand-delete" brand.id %}' role="button">DELETE</a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}


<div class="table-responsive-sm px-1">
    <table class="table table-striped table-sm">
        <thead>
            <tr class="table table-light ">
                <th scope="col">Generation</th>
                <th scope="col">RAM</th>
                <th scope="col">Brands</th>
                <th scope="col">Minimum Price</th>
                <th scope="col">Maximum Price</th>
                <th scope="col">Action</th>
                
            </tr>
        </thead>
            {% for gen in gen_list %}
                <tbody>
                    <tr>
                        <td>{{gen.generation}}</td>
                        <td>{{gen.RAM}}GB</td>
                        <td>{{gen.brands}}</td>
                        <td>Min. Price:{{gen.price_min}}</td>
                        <td>Max. Price:{{gen.price_max}}</td>
                        <td><a class="btn btn-secondary btn-sm" href='{% url "chub:gen-update" gen.id %}' role="button">UPDATE</a>
                            <a class="btn btn-danger btn-sm" href='{% url "chub:gen-delete" gen.id %}' role="button">DELETE</a></td>
                    <tr>
                </tbody>
            {% endfor %}
            </tr>
        </thead>
    </table>
</div>

computer/templates/computer/computergeneration_confirm_delete.html
{%extends "computer/index.html"%}
{%block title%} Deleting Computer Generation{% endblock%}

{% block content %}
</h3>Are you sure about deleting the computer generation data?</h3>
<p>Computer Generation: {{computergeneration}}</p>

<form method="POST">
    {% csrf_token %}
    <input type= "submit" value= "Confirm Delete">
</form>
{% endblock %}

computer/templates/computer/computergeneration_form.html
{% extends "computer/index.html" %}
{% block title %}
Add Computer Generation Form
{% endblock %}


{% comment %} {% block content %}

<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type= 'submit' value= 'Submit'>
<form>
{% endblock  %} {% endcomment %}


{% block content %}
    <div class = "row justify-content-center ">
        <div class="col-lg-4">
            <form method= "POST" enctype= "multipart/form-data" >
                {% csrf_token %}
                {{ form.generation.value}}
                <p>{{form.price_min.value}} (To check the return value!!!)</p>

                <div class="mb-3">
                    <label for="{{ form.generation.id_for_label }}" class="form-label">Generation:</label>
                    <input type="text" class="form-control" name="{{ form.generation.name }}" id="{{ form.generation.id_for_label }}" value="{% if form.generation.value %} {{ form.generation.value }} {% else %} {% endif %} ">
                </div>

                <div class=" mb-3">
                    <label for="{{ form.price_min.id_for_label }}" class="form-label">Minimum Price: </label>
                    <input type= "number" class= "form-control" name= "{{ form.price_min.name }}" id= "{{form.price_min.id_for_label}}" value= "{{form.price_min.value}}">
                </div>

                <div class=" mb-3">
                    <label for="{{ form.price_max.id_for_label }}" class="form-label">Maximum Price: </label>
                    <input type="number" class="form-control" name="{{ form.price_max.name }}" id="{{ form.price_max.id_for_label }}" value="{{ form.price_max.value }}">
                </div>

                <div class=" mb-3">
                    <label for="{{ form.RAM.id_for_label }}" class="form-label">RAM: </label>
                    <input class="form-control" name="{{ form.RAM.name }}" type="number" id="{{ form.RAM.id_for_label }}" value= "{{ form.RAM.value }}">
                </div>

                
                <p>{{form.initial}}</p>

                <div class="input-group mb-3">
                    <label class="input-group" for="{{ form.brands.id_for_label }}">Brands</label>
                    <select class="form-select" id="{{ form.brands.id_for_label }}" name="{{ form.brands.name }}" value= "{{ form.brands.value }}">
                        <option value="" disabled selected >Select a Brand </option>
                        {% for brand in form.brands.field.queryset %}
                            <option value= "{{ brand.pk}}">{{brand.brand_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                  
                <div>
                    <button class= "btn btn-secondary" type="submit">Submit</button>   
                </div>

            </form>
        </div>
    </div>
{% endblock%}

computer/templates/computer/computergeneration_list.html
{% extends "computer/index.html" %}
 
{% block title %} 
    Computer Generation List 
{% endblock %}

{% block content %}
    <div class="d-flex flex-column">
        <div>
            <a class="btn btn-primary float-end m-3" href='{% url "chub:gen-create-form" %}' role="button">Add Generation</a>
        </div>
        <div class="table-responsive-sm ">
            <table class="table table-striped ">
                <thead>
                    <tr class="table table-light ">
                        <th scope="col">S.N.</th>
                        <th scope="col">Generation</th>
                        <th scope="col">RAM</th>
                        <th scope="col">Brands</th>
                        <th scope="col">Minimum Price</th>
                        <th scope="col">Maximum Price</th>
                        <th scope="col">Action</th>
                        
                    </tr>
                </thead>
                    {% for gen in gen_list %}
                        <tbody>
                            <tr>
                                <td scope="row">{{forloop.counter}}</td>
                                <td>{{gen.generation}}</td>
                                <td>{{gen.RAM}}GB</td>
                                <td>{{gen.brands}}</td>
                                <td>Min. Price:{{gen.price_min}}</td>
                                <td>Max. Price:{{gen.price_max}}</td>
                                <td><a class="btn btn-secondary btn-sm" href='{% url "chub:gen-update" gen.id %}' role="button">UPDATE</a>
                                    <a class="btn btn-danger btn-sm" href='{% url "chub:gen-delete" gen.id %}' role="button">DELETE</a></td>
                            <tr>
                        </tbody>
                    {% endfor %}
                    </tr>
                </thead>
            </table>
        </div>
    </div>

{% endblock  %}

computer/templates/computer/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title> {% block title %} Home{% endblock %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
  </head>
  <body>
    
    {% comment %} <h1><a href= >Computer Hub </a></h1> {% endcomment %}
    <nav class="px-2 py-6 navbar navbar-expand-lg bg-light-subtle fs-6 fw-semibold">
      <div class="container-fluid">
        <a class="navbar-brand text-info-emphasis " href="{% url 'chub:index' %}"><img src="/media/uploadimages/hublogo.png"></a>
        <a class="navbar-brand text-info-emphasis " href="{% url 'chub:index' %}">Computer Hub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% comment %} <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'chub:index' %}">Home</a>
            </li> {% endcomment %}
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Goto
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href='{% url "chub:brand-list" %}'>Computer Brand</a></li>
                <li><a class="dropdown-item" href='{% url "chub:genlist" %}'>Computer Generation</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href='{% url "chub:index" %}'>View Computer List</a></li>
              </ul>
            </li>
            
          </ul>
          {% comment %} <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> {% endcomment %}
        </div>
      </div>
    </nav>
    
    <div class= "p-2 ">
      {% block content %}
        <p>
            <li><a href= '{% url "chub:brand-list" %}'>View Computer Brand</a></li>
            <li><a href= '{% url "chub:genlist" %}'> View Computer Generation</a></li>
            {% comment %} <li><a href= '{% url "chub:create-form" %}''> ADD Computer Here</a></li> {% endcomment %}
        </p>
      {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>